## Amazon Product Sales Data Cleaning with Pandas

In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv("amazon_products_sales_data_uncleaned.csv")

In [4]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-30 19:56:33

## Inspection of Data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [6]:
df.describe().round()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
count,42675,41651,41651,39458,30926,42675,42675,42675,42675,42675,28022,30955,3408,42675,40606,42675
unique,8808,31,4413,59,2576,3466,911,12,2,42,1,298,16,8038,40606,1559
top,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.6 out of 5 stars,25,100+ bought in past month,29.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"Delivery Mon, Sep 1",Small Business,https://m.media-amazon.com/images/I/51Xr76m2WL...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-21 11:15:31
freq,744,6151,626,8801,825,21031,30364,40814,35664,40727,28022,6189,1341,1461,1,33

In [7]:
df.isnull().sum()

title                           0
rating                       1024
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [8]:
df[df.duplicated()].shape

(0, 16)

In [9]:
df.shape

(42675, 16)

- droping images_url and product-url because they do not contribute to analytical insights

In [10]:
df = df.drop(["image_url","product_url"], axis=1)

In [11]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'collected_at'],
      dtype='object')

# Handling Missing Values

##### Title

In [12]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'collected_at'],
      dtype='object')

In [13]:
df.isnull().sum()

title                           0
rating                       1024
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

#### ratings

In [14]:

df["rating"].isnull().sum()

np.int64(1024)

In [15]:
df["rating"].unique()

array(['4.6 out of 5 stars', '4.3 out of 5 stars', '4.8 out of 5 stars',
       '4.5 out of 5 stars', '4.0 out of 5 stars', '4.7 out of 5 stars',
       '4.2 out of 5 stars', '4.4 out of 5 stars', '4.1 out of 5 stars',
       '4.9 out of 5 stars', '3.9 out of 5 stars', '3.8 out of 5 stars',
       '2.8 out of 5 stars', '3.6 out of 5 stars', '3.7 out of 5 stars',
       '3.4 out of 5 stars', '3.5 out of 5 stars', nan,
       '5.0 out of 5 stars', '3.3 out of 5 stars', '2.4 out of 5 stars',
       '2.9 out of 5 stars', '3.2 out of 5 stars', '3.0 out of 5 stars',
       '1.0 out of 5 stars', '2.3 out of 5 stars', '3.1 out of 5 stars',
       '2.5 out of 5 stars', '2.7 out of 5 stars', '1.5 out of 5 stars',
       '2.6 out of 5 stars', '2.0 out of 5 stars'], dtype=object)

In [16]:
df["rating"].describe()

count                  41651
unique                    31
top       4.6 out of 5 stars
freq                    6151
Name: rating, dtype: object

In [17]:
df["rating"].value_counts()

rating
4.6 out of 5 stars    6151
4.4 out of 5 stars    5525
4.5 out of 5 stars    5359
4.7 out of 5 stars    4664
4.8 out of 5 stars    4230
4.3 out of 5 stars    2927
4.2 out of 5 stars    2837
4.1 out of 5 stars    1959
4.0 out of 5 stars    1465
3.9 out of 5 stars    1316
3.8 out of 5 stars    1083
5.0 out of 5 stars     995
4.9 out of 5 stars     704
3.6 out of 5 stars     666
3.7 out of 5 stars     604
3.2 out of 5 stars     363
3.5 out of 5 stars     242
3.4 out of 5 stars     216
3.0 out of 5 stars     148
2.0 out of 5 stars     143
2.7 out of 5 stars      15
1.5 out of 5 stars      15
3.3 out of 5 stars       6
2.8 out of 5 stars       4
1.0 out of 5 stars       4
2.4 out of 5 stars       3
2.9 out of 5 stars       2
3.1 out of 5 stars       2
2.3 out of 5 stars       1
2.5 out of 5 stars       1
2.6 out of 5 stars       1
Name: count, dtype: int64

In [18]:
df["rating"] = df['rating'].str.extract(r'(\d+\.\d+)').astype(float)

In [19]:
df["rating"] = df['rating'].fillna(df['rating'].median())

In [20]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### number_of_reviews

In [21]:
df["number_of_reviews"].describe()

count     41651
unique     4413
top          25
freq        626
Name: number_of_reviews, dtype: object

In [22]:
df["number_of_reviews"].value_counts()

number_of_reviews
25        626
1         524
8         478
17        409
30        409
         ...
48,468      1
72,360      1
67,965      1
53,340      1
8,962       1
Name: count, Length: 4413, dtype: int64

In [23]:
df['number_of_reviews'].head(10)

0       375
1     2,457
2     3,044
3    35,882
4    28,988
5    44,522
6    13,466
7    38,105
8     4,380
9     7,308
Name: number_of_reviews, dtype: object

In [24]:
df['number_of_reviews'] = (
    df['number_of_reviews']
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [25]:
df["number_of_reviews"].isnull().sum()

np.int64(1024)

In [26]:
df['number_of_reviews'].fillna(df["number_of_reviews"].median(), inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_33652\1412695407.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['number_of_reviews'].fillna(df["number_of_reviews"].median(), inplace=True)

In [27]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### bought_in_last_month

In [28]:
df["bought_in_last_month"].head()

0    300+ bought in past month
1     6K+ bought in past month
2     2K+ bought in past month
3    10K+ bought in past month
4    10K+ bought in past month
Name: bought_in_last_month, dtype: object

In [29]:
df["bought_in_last_month"].unique()

array(['300+ bought in past month', '6K+ bought in past month',
       '2K+ bought in past month', '10K+ bought in past month',
       '100K+ bought in past month', nan, '100+ bought in past month',
       '1K+ bought in past month', '500+ bought in past month',
       '80K+ bought in past month', '70K+ bought in past month',
       '50K+ bought in past month', '40K+ bought in past month',
       '60K+ bought in past month', '20K+ bought in past month',
       '30K+ bought in past month', '9K+ bought in past month',
       '50+ bought in past month', '5K+ bought in past month',
       'List Price:', '7K+ bought in past month',
       '4K+ bought in past month', 'Typical:',
       '200+ bought in past month', '8K+ bought in past month',
       'ESRB Rating: Everyone', '3K+ bought in past month',
       'No featured offers available', 'List:',
       'ESRB Rating: Rating Pending', '900+ bought in past month',
       '400+ bought in past month', '700+ bought in past month',
       'This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.',
       '800+ bought in past month', 'More Buying Choices',
       '600+ bought in past month', '($1,999.75$1,999.75/100 cm)',
       'Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.',
       'ESRB Rating: Everyone 10+', 'ESRB Rating: Adults Only',
       '($54.26$54.26/count)', 'New Price:', '($1,315.78$1,315.78/kg)',
       'Alexa Built-in devices let you talk directly to Alexa, allowing you to play music, control your smart home, get news, weather, and more using your voice.',
       '($4,813.00$4,813.00/100 cm)', '($433.33$433.33/count)',
       '($252.00$252.00/count)', '($1,080.00$1,080.00/kg)',
       '($46.81$46.81/oz)', '($828.56$828.56/kg)', '($53.33$53.33/count)',
       '($30.00$30.00/count)', '($766.33$766.33/in)',
       '90K+ bought in past month', '($2.18$2.18/count)',
       '($5.27$5.27/in)', '($179.99$179.99/count)', '($43.69$43.69/oz)',
       'Was:'], dtype=object)

In [30]:
import numpy as np

def clean_bought(x):
    if pd.isna(x):
        return np.nan

    x = str(x)

    if 'bought in past month' in x:
        num = x.split('+')[0]

        if 'K' in num:
            return float(num.replace('K', '')) * 1000

        return float(num)

    return np.nan

df['bought_in_last_month'] = df['bought_in_last_month'].apply(clean_bought)

In [31]:
df['bought_in_last_month'].isnull().sum()

np.int64(10511)

In [32]:
df['bought_in_last_month'].fillna(
    df['bought_in_last_month'].median(),
    inplace=True
)

C:\Users\akhil\AppData\Local\Temp\ipykernel_33652\1699490390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bought_in_last_month'].fillna(

In [33]:
df['bought_in_last_month'].isnull().sum()

np.int64(0)

In [34]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### current/discounted_price

In [35]:
df['current/discounted_price'].unique()

array(['89.68', '9.99', '314.00', ..., '1,579.99', '20.14', '1,252.29'],
      dtype=object)

In [36]:
df['current/discounted_price'].describe()

count     30926
unique     2576
top       29.99
freq        825
Name: current/discounted_price, dtype: object

In [37]:
df['current/discounted_price'] = pd.to_numeric(df['current/discounted_price'].str.replace(",",""), errors='coerce')

In [38]:
df['current/discounted_price'].fillna(df['current/discounted_price'].median(), inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_33652\1749864171.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['current/discounted_price'].fillna(df['current/discounted_price'].median(), inplace=True)

In [39]:
df['current/discounted_price'].isnull().sum()

np.int64(0)

In [40]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

#### buy_box_availabilty

In [41]:
df['buy_box_availability'].isnull().sum()

np.int64(14653)

In [42]:
df['buy_box_availability'].unique()

array(['Add to cart', nan], dtype=object)

In [43]:
df['buy_box_availability'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: buy_box_availability
Non-Null Count  Dtype
--------------  -----
28022 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [44]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    28022
Name: count, dtype: int64

In [45]:
df['buy_box_availability'].fillna("Unknown",inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_33652\660643703.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['buy_box_availability'].fillna("Unknown",inplace=True)

In [46]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### delivery_details

In [47]:
df['delivery_details'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: delivery_details
Non-Null Count  Dtype
--------------  -----
30955 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [48]:
df['delivery_details'].unique()

array(['Delivery Mon, Sep 1', 'Delivery Fri, Aug 29', nan,
       'Delivery Sep 1 - 11', 'Delivery Sep 4 - 9', 'Delivery Sep 8 - 30',
       'Delivery Aug 28 - Sep 1', 'Delivery Sep 1 - 2',
       'Delivery Aug 28 - Sep 3', 'Delivery Sep 1 - 9',
       'Delivery Aug 29 - Sep 2', 'Delivery Sep 9 - 25',
       'Delivery Aug 29 - Sep 12', 'Delivery Sep 1 - 3',
       '$42.19 delivery', 'Delivery Tue, Sep 2', 'Delivery Sep 1 - 4',
       'Delivery Sep 1 - 12', 'Delivery Aug 29 - Sep 3',
       'Delivery Sep 3 - 11', 'Delivery Sep 3 - 15', '$41.20 delivery',
       '$40.35 delivery', 'Delivery Sep 1 - 8', 'Delivery Aug 29 - Sep 4',
       'Delivery Sep 3 - 23', 'Ships to Pakistan', '$73.42 delivery',
       '$40.34 delivery', 'Delivery Sep 8 - 26', '$58.05 delivery',
       'Delivery Sep 8 - 25', '$40.13 delivery', '$43.43 delivery',
       'Delivery Sep 8 - Oct 7', 'Delivery Sep 8 - 24',
       'Delivery Sep 22 - Nov 4', '$40.89 delivery', '$44.08 delivery',
       'Delivery Aug 27 - Sep 1', 'Delivery Sep 8 - 23',
       '$40.39 delivery', '$9.03 delivery Sep 8 - 22', '$41.77 delivery',
       'Delivery Sep 1 - 17', '$59.99 delivery Aug 28 - Sep 4',
       '$41.59 delivery', 'Delivery Sep 8 - 22', '$41.99 delivery',
       '$66.02 delivery Sep 3 - 8', 'Delivery Sep 2 - 11',
       '$57.80 delivery', '$63.99 delivery', 'Delivery Sep 4 - 25',
       'Delivery Sep 5 - 16', 'Delivery Aug 29 - Sep 11',
       'Delivery Sep 8 - 17', 'Delivery Sep 2 - 9',
       'Delivery Sep 10 - 24', '$46.68 delivery', 'Delivery Sep 9 - 26',
       'Delivery Sep 15 - 26', '$75.17 delivery', '$40.44 delivery',
       'Delivery Sep 8 - 16', 'Delivery Sep 9 - 16',
       'Delivery Sep 2 - 15', '$46.48 delivery',
       'Delivery Aug 28 - Sep 2', 'Delivery Sep 9 - 23',
       'Delivery Sep 15 - 30', 'Delivery Sep 5 - 15', '$178.71 delivery',
       'Delivery Sep 3 - 9', '$58.95 delivery', '$81.11 delivery',
       'Delivery Sep 5 - 29', '$64.58 delivery Sep 3 - 8',
       '$67.19 delivery', 'Delivery Sep 16 - Oct 3',
       'Delivery Sep 8 - Oct 1', 'Delivery Sep 4 - 12', '$49.02 delivery',
       'Delivery Sep 17 - Oct 28', 'Delivery Fri, Sep 19',
       'Delivery Sep 8 - 19', 'Delivery Sep 8 - 18',
       'Delivery Sep 5 - 23', 'Delivery Aug 28 - Sep 4',
       'Delivery Mon, Sep 8', 'Delivery Sep 8 - Oct 3',
       'Delivery Sep 9 - Oct 3', '$65.29 delivery',
       'Delivery Sep 15 - 29', '$241.54 delivery',
       '$6.93 delivery Sep 8 - 22', 'Delivery Sep 4 - 16',
       'Delivery Sep 15 - Oct 24', 'Delivery Sep 8 - 29',
       '$44.83 delivery', 'Delivery Sep 2 - 4', 'Delivery Sep 4 - 11',
       '$83.65 delivery', '$60.05 delivery Sep 3 - 8', '$57.26 delivery',
       '$71.18 delivery', 'Delivery Sep 12 - 30', '$69.19 delivery',
       'Delivery Aug 27 - Sep 2', 'Delivery Aug 29 - Sep 1',
       'Delivery Sep 10 - 30', 'Delivery Sep 8 - 11', '$65.19 delivery',
       'Delivery Sep 3 - 16', 'Delivery Sep 1 - 16', '$111.61 delivery',
       '$5.99 delivery Sep 12 - Oct 3', '$227.02 delivery',
       '$251.88 delivery Sep 8 - 22', 'Delivery Thu, Sep 11',
       '$42.43 delivery Sep 12 - Oct 2', '$54.41 delivery',
       '$140.09 delivery', '$101.48 delivery', '$49.94 delivery',
       '$43.73 delivery', '$40.37 delivery', '$55.86 delivery',
       '$43.93 delivery', '$35.31 delivery Sep 12 - Oct 2',
       '$42.70 delivery Aug 28 - Sep 4', 'Delivery Thu, Sep 4',
       'Delivery Sep 2 - 10', 'Delivery Fri, Sep 5',
       'Delivery Thu, Aug 28', 'Delivery Fri, Sep 12',
       'Delivery Sep 17 - Oct 1', 'Delivery Wed, Sep 10',
       '$10.89 delivery', 'Delivery Sep 12 - Oct 6', 'Delivery Sep 2 - 8',
       '$43.52 delivery', 'Delivery Sep 15 - Oct 1',
       '$42.70 delivery Aug 29 - Sep 5', '$39.79 delivery Sep 15 - Oct 3',
       'Delivery Tue, Sep 9', 'Delivery Sep 22 - Oct 14',
       '$59.70 delivery', '$285.30 delivery Sep 4 - 15',
       'Delivery Wed, Sep 3', '$5.99 delivery Sep 15 - Oct 6',
       '$40.80 delivery Sep 9 - 23', '$59.99 delivery Aug 29 - Sep 5',
       'Delivery Sep 1 - 15', 'Delivery Sep 3 - 10',
       'Delivery Sep 3 - 12', 'Delivery Sep 19 - Oct 30',
       '$49 delivery Sep 9 - 23', 'Delivery Sep 10 - 17',
       'Delivery Sep 10 - 18', '$17.49 delivery', '$61.55 delivery',
       'Delivery Sep 11 - Oct 10', '$48.12 delivery',
       'Delivery Mon, Sep 15', 'FREE delivery Sep 9 - 24',
       'Delivery Sep 8 - 15', 'Delivery Sep 12 - 23',
       'Delivery Sep 2 - 16', '$60.60 delivery Sep 12 - 29',
       '$118.24 delivery', '$42.59 delivery Sep 15 - Oct 6',
       'Delivery Sep 12 - Oct 1', 'Delivery Sep 5 - 11',
       'Delivery Sep 15 - 23', 'Delivery Sep 5 - 24',
       '$40.85 delivery Sep 9 - 23', 'Delivery Sep 3 - 18',
       'Delivery Sep 19 - Oct 1', 'Delivery Sep 2 - 3',
       '$70.80 delivery Sep 12 - 29', 'Delivery Sep 11 - 29',
       '$42.59 delivery Sep 15 - Oct 3', 'Delivery Sep 22 - Nov 3',
       '$108.33 delivery', '$251.45 delivery Sep 9 - 23',
       'Delivery Sep 17 - Oct 7', 'Delivery Sep 3 - 4',
       'Delivery Sep 8 - 12', 'Delivery Sep 9 - 12', '$146.58 delivery',
       '$70 delivery', 'Delivery Sep 10 - Oct 2', '$11.17 delivery',
       '$77.25 delivery Sep 9 - 24', 'Delivery Sep 11 - 22',
       'Delivery Sep 8 - 10', '$63.31 delivery',
       'Delivery Fri, Sep 5Or fastest delivery Thu, Aug 28',
       'Delivery Thu, Sep 4Or fastest delivery Thu, Aug 28',
       'Delivery Tue, Sep 9Or fastest delivery Thu, Aug 28',
       'Delivery Thu, Sep 11Or fastest delivery Thu, Aug 28',
       '$9.11 delivery', '$5.15 delivery Sep 15 - Oct 6',
       '$5.43 delivery Sep 15 - Oct 6',
       'Delivery Mon, Sep 8Or fastest delivery Thu, Aug 28',
       'Delivery Sep 12 - Oct 2', 'Delivery Sep 10 - Oct 6',
       '$48.44 delivery', '$8.09 delivery', 'Delivery Sep 11 - Oct 9',
       'Delivery Mon, Sep 8Or fastest delivery Wed, Sep 3',
       '$54.46 delivery', 'Delivery Sep 9 - 15',
       'Delivery Sep 17 - Oct 8', 'Delivery Sep 5 - 9',
       'Delivery Sep 11 - 30', 'Delivery Sep 10 - 29',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Sun, Aug 31',
       'FREE delivery Wed, Sep 3Or fastest delivery Sun, Aug 31',
       'FREE delivery Thu, Sep 4Or fastest delivery Wed, Sep 3',
       'FREE delivery Tue, Sep 9Or fastest delivery Thu, Sep 4',
       'FREE delivery Tomorrow, Aug 30',
       '$38.09 delivery Sep 4 - 8Or fastest delivery Thu, Sep 4',
       'FREE delivery Wed, Sep 3',
       'FREE delivery Sep 13 - 23Or fastest delivery Sep 13 - 19',
       'FREE delivery Sep 3 - 4',
       'FREE delivery Sep 4 - 9Or fastest delivery Sep 4 - 6',
       'FREE delivery Tue, Sep 9',
       'FREE delivery Wed, Sep 3Or fastest delivery Mon, Sep 1',
       'FREE delivery Sep 13 - 22Or fastest delivery Sep 13 - 18',
       'FREE delivery Sep 4 - 7Or fastest delivery Sep 4 - 5',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Mon, Sep 1',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Tue, Sep 2',
       'FREE delivery Fri, Sep 5',
       'FREE delivery Sep 5 - 9Or fastest delivery Tue, Sep 2',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 8',
       '$42.73 delivery',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 9',
       'Delivery Sun, Aug 31', 'FREE delivery Sep 4 - 8',
       'FREE delivery Sep 4 - 6Or fastest delivery Thu, Sep 4',
       'FREE delivery Thu, Sep 11',
       'FREE delivery Sep 12 - 22Or fastest delivery Sep 11 - 18',
       'FREE delivery Sep 4 - 7Or fastest delivery Sep 2 - 5',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Mon, Sep 1',
       'FREE delivery Sep 5 - 9', 'FREE delivery Sep 4 - 5',
       'FREE delivery Sep 3 - 5', 'FREE delivery Sep 15 - 18',
       'FREE delivery Sep 16 - 17', 'FREE delivery Tue, Sep 2',
       'FREE delivery Sep 4 - 8Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 9 - 11Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 5',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Tue, Sep 2',
       'FREE delivery Sep 9 - 12Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 5 - 9Or fastest delivery Sep 4 - 5',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Sun, Aug 31',
       'FREE delivery Thu, Sep 4',
       'FREE delivery Sep 8 - 12Or fastest delivery Tue, Sep 9',
       'FREE delivery Sep 11 - 22Or fastest delivery Sep 11 - 18',
       'FREE delivery Wed, Sep 3Or fastest delivery Tomorrow, Aug 30',
       'FREE delivery Sep 5 - 11Or fastest delivery Sep 4 - 8',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Aug 30',
       'FREE delivery Tue, Sep 9Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 4 - 5Or fastest delivery Tue, Sep 2',
       'FREE delivery Tue, Sep 9 on $35 of items shipped by Amazon',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 7',
       'FREE delivery Sep 5 - 6Or fastest delivery Thu, Sep 4',
       '$59.99 delivery Sep 8 - 12', '$41.15 delivery',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Aug 31',
       'FREE delivery',
       'FREE delivery Sat, Sep 6Or fastest delivery Mon, Sep 1',
       'FREE delivery Thu, Sep 4Or fastest delivery Tomorrow, Aug 31',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by Amazon',
       'FREE delivery Sep 5 - 9Or fastest delivery Thu, Sep 4',
       'FREE delivery Fri, Sep 5Or fastest delivery Thu, Sep 4',
       'FREE delivery Sep 4 - 8Or fastest delivery Thu, Sep 4',
       'FREE delivery Mon, Sep 8',
       'FREE delivery Sep 5 - 9Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 5 - 10Or fastest delivery Thu, Sep 4',
       'Delivery Sep 9 - 24',
       'FREE delivery Sep 4 - 7Or fastest delivery Thu, Sep 4',
       'FREE delivery Fri, Sep 5 on $35 of items shipped by AmazonOr fastest delivery Wed, Sep 3',
       'Delivery Sep 15 - Oct 3',
       'FREE delivery Thu, Sep 4Or fastest delivery Mon, Sep 1',
       'FREE delivery Tomorrow 8\u202fAM - 8\u202fPM',
       'FREE delivery Fri, Sep 5Or fastest delivery Tue, Sep 2',
       'FREE delivery Sep 9 - 10', 'Delivery Sep 29 - Oct 20',
       'FREE delivery Thu, Sep 4Or fastest delivery Tue, Sep 2',
       'Delivery Sep 15 - 25', 'Delivery Sep 16 - 29',
       'Delivery Sep 16 - 30',
       'FREE delivery Sep 5 - 10Or fastest delivery Sep 4 - 6',
       'FREE delivery Sep 23 - Oct 18Or fastest delivery Sep 23 - Oct 13',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Wed, Sep 3'],
      dtype=object)

In [49]:
df['delivery_details'].describe()

count                   30955
unique                    298
top       Delivery Mon, Sep 1
freq                     6189
Name: delivery_details, dtype: object

In [50]:
df['delivery_details'].isnull().sum()

np.int64(11720)

In [51]:
df['delivery_details'] = df['delivery_details'].str.extract(r'Delivery\s+(.*)')

- Forward fill was used because nearby records had similar delivery information. In a production environment, this decision should be validated with domain knowledge.

In [52]:
df['delivery_details'] = df['delivery_details'].ffill()

In [53]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details                0
sustainability_badges       39267
collected_at                    0
dtype: int64

### sustainabilty_badges

In [54]:
df['sustainability_badges'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: sustainability_badges
Non-Null Count  Dtype
--------------  -----
3408 non-null   object
dtypes: object(1)
memory usage: 333.5+ KB

In [55]:
df['sustainability_badges'].describe()

count               3408
unique                16
top       Small Business
freq                1341
Name: sustainability_badges, dtype: object

In [56]:
df['sustainability_badges'].unique()

array(['Carbon impact', nan, 'Energy efficiency',
       'Safer chemicals +1 more', 'Small Business',
       '1 sustainability certification', 'Works with Alexa',
       'Manufacturing practices', 'Forestry practices', 'Alexa Built-in',
       'Energy efficiency +3 more', 'Recycled materials',
       'Safer chemicals +2 more', 'Energy efficiency +1 more',
       'Recycled materials +3 more', 'Recycled materials +2 more',
       'Made in Italy'], dtype=object)

In [57]:
df.drop('sustainability_badges', axis=1, inplace=True)

In [58]:
df.isnull().sum()

title                       0
rating                      0
number_of_reviews           0
bought_in_last_month        0
current/discounted_price    0
price_on_variant            0
listed_price                0
is_best_seller              0
is_sponsored                0
is_couponed                 0
buy_box_availability        0
delivery_details            0
collected_at                0
dtype: int64

### fixing Inconsitent formating

In [59]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [60]:
df[df.duplicated()].shape

(0, 13)

In [61]:
df['title'].unique()

array(['BOYA BOYALINK 2 Wireless Lavalier Microphone for iPhone Camera Android, Mini Lapel Micophone Wireless, 48 KHz 24 Bit, 6mm Mic, 1000ft, 30h Use, Noise Cancelling, Clip on Mic USB-C/Lightning/3.5mm TRS',
       'LISEN USB C to Lightning Cable, 240W 4 in 1 Charging Cable 6.6FT, Chubby USB A/C to C/Lightning with Light for iPhone 16e 15 14 Pro/MacBook Air 17/iPad/Samsung/Switch 2, Multi Chargers for All Devices',
       'DJI Mic 2 (2 TX + 1 RX + Charging Case), Wireless Lavalier Microphone, Intelligent Noise Cancelling, 32-bit Float Internal Recording, 820 ft.(250m) Range, Microphone for iPhone, Android, Camera',
       ...,
       'Monster Clarity 8.0 Hybrid Active Noise Cancelling Wireless Earbuds, 42dB in-Ear ANC Earphones Deep Bass with 6 Mics, Bluetooth 5.2, 50H Play Time with Wireless Charging Case,Blue',
       'Audio-Technica HP-EP Replacement Ear Pads for M Series Headphones',
       'Apple 2022 MacBook Air Laptop with M2 chip (13.6-inch, 8GB RAM, 256GB SSD Storage) Starlight (Renewed)'],
      dtype=object)

In [62]:
df['title'] = df['title'].str.strip()

In [63]:
df['title'] = df['title'].str.lower()

In [64]:
df['title'].duplicated().sum()

np.int64(33868)

In [65]:
df['title'].value_counts()

title
duracell coppertop 9v battery, 6 count (pack of 1), 9 volt battery with long-lasting power, all-purpose alkaline 9v battery for household and office devices                                               744
energizer max aa batteries (16 pack), double a alkaline batteries                                                                                                                                          566
trx training 6 month on-demand membership - unlimited access to expert-led workouts, personalized programs, strength, cardio & recovery - train anytime                                                    456
kodak 10.1 inch wifi digital picture frame,1280x800 hd ips touch screen, electronic smart photo frame with 32 gb memory, auto-rotate, instantly share photos/videos anywhere                               438
belkin magsafe-compatible charger, 3-in-1 wireless charging station, qi2-certified 15w wireless charge for apple iphone 16 series, apple watch, airpods w/non-slip base, 40w included - black              377
                                                                                                                                                                                                          ...
amazon basics multipurpose copy printer paper, 20 lb, 8.5 x 11 inches, 8 reams (4,000 sheets), 92 bright, white                                                                                              1
texas instruments ti-30xiis scientific calculator, black with blue accents                                                                                                                                   1
apple 2025 macbook air 13-inch laptop with m4 chip: built for apple intelligence, 13.6-inch liquid retina display, 16gb unified memory, 256gb ssd storage, 12mp center stage camera, touch id; midnight      1
amazon basics 48-pack aa alkaline high-performance batteries, 1.5 volt, 10-year shelf life                                                                                                                   1
apple ipad 11-inch: a16 chip, 11-inch model, liquid retina display, 128gb, wi-fi 6, 12mp front/12mp back camera, touch id, all-day battery life — blue                                                       1
Name: count, Length: 8807, dtype: int64

In [66]:
df['rating'].isnull().sum()

np.int64(0)

In [67]:
df['rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: rating
Non-Null Count  Dtype
--------------  -----
42675 non-null  float64
dtypes: float64(1)
memory usage: 333.5 KB

In [68]:
df['rating'].describe()

count    42675.000000
mean         4.401844
std          0.382636
min          1.000000
25%          4.200000
50%          4.500000
75%          4.600000
max          5.000000
Name: rating, dtype: float64

In [69]:
df['rating'].head(20)

0     4.6
1     4.3
2     4.6
3     4.6
4     4.8
5     4.6
6     4.5
7     4.6
8     4.0
9     4.7
10    4.7
11    4.8
12    4.2
13    4.4
14    4.7
15    4.7
16    4.8
17    4.7
18    4.8
19    4.6
Name: rating, dtype: float64

In [70]:
df['number_of_reviews'].isnull().sum()

np.int64(0)

In [71]:
df['number_of_reviews'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: number_of_reviews
Non-Null Count  Dtype
--------------  -----
42675 non-null  float64
dtypes: float64(1)
memory usage: 333.5 KB

In [72]:
df['number_of_reviews'].head(20)

0        375.0
1       2457.0
2       3044.0
3      35882.0
4      28988.0
5      44522.0
6      13466.0
7      38105.0
8       4380.0
9       7308.0
10    865598.0
11      1914.0
12       152.0
13     12076.0
14      7235.0
15     48468.0
16    198512.0
17    625776.0
18     88965.0
19      1909.0
Name: number_of_reviews, dtype: float64

In [73]:
df['number_of_reviews'].nunique()

4413

In [74]:
df['number_of_reviews'] = df['number_of_reviews'].astype('int64')

In [75]:
(df['number_of_reviews'] < 0).sum()

np.int64(0)

In [76]:
df['bought_in_last_month'].isnull().sum()

np.int64(0)

In [77]:
df['bought_in_last_month'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: bought_in_last_month
Non-Null Count  Dtype
--------------  -----
42675 non-null  float64
dtypes: float64(1)
memory usage: 333.5 KB

In [78]:
df['bought_in_last_month'].unique()

array([3.e+02, 6.e+03, 2.e+03, 1.e+04, 1.e+05, 2.e+02, 1.e+02, 1.e+03,
       5.e+02, 8.e+04, 7.e+04, 5.e+04, 4.e+04, 6.e+04, 2.e+04, 3.e+04,
       9.e+03, 5.e+01, 5.e+03, 7.e+03, 4.e+03, 8.e+03, 3.e+03, 9.e+02,
       4.e+02, 7.e+02, 8.e+02, 6.e+02, 9.e+04])

In [79]:
df['bought_in_last_month'].value_counts()

bought_in_last_month
200.0       16156
100.0        8801
50.0         5967
300.0        2842
500.0        2351
1000.0       2084
400.0        1436
20000.0       772
2000.0        426
800.0         280
3000.0        249
600.0         229
10000.0       229
4000.0        196
5000.0        120
700.0         102
90000.0        92
6000.0         81
900.0          63
7000.0         49
9000.0         44
8000.0         36
30000.0        28
40000.0        14
100000.0       13
50000.0         6
70000.0         4
60000.0         3
80000.0         2
Name: count, dtype: int64

In [80]:
df['bought_in_last_month'].head(20)

0        300.0
1       6000.0
2       2000.0
3      10000.0
4      10000.0
5     100000.0
6      10000.0
7      10000.0
8        200.0
9      10000.0
10    100000.0
11     10000.0
12       100.0
13      1000.0
14       500.0
15    100000.0
16     80000.0
17    100000.0
18    100000.0
19     10000.0
Name: bought_in_last_month, dtype: float64

In [81]:
(df['bought_in_last_month'] % 1 != 0).sum()

np.int64(0)

In [82]:
df['bought_in_last_month'] = df['bought_in_last_month'].astype('int64')

In [83]:
df['bought_in_last_month'].head(20)

0        300
1       6000
2       2000
3      10000
4      10000
5     100000
6      10000
7      10000
8        200
9      10000
10    100000
11     10000
12       100
13      1000
14       500
15    100000
16     80000
17    100000
18    100000
19     10000
Name: bought_in_last_month, dtype: int64

In [84]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [85]:
df['current/discounted_price'].isnull().sum()

np.int64(0)

In [86]:
df['current/discounted_price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: current/discounted_price
Non-Null Count  Dtype
--------------  -----
42675 non-null  float64
dtypes: float64(1)
memory usage: 333.5 KB

In [87]:
df['current/discounted_price'].unique()

array([  89.68,    9.99,  314.  , ..., 1579.99,   20.14, 1252.29])

In [88]:
df['current/discounted_price'].value_counts()

current/discounted_price
77.00     11883
29.99       825
119.99      695
13.99       585
24.99       502
          ...
212.36        1
882.99        1
9.89          1
188.06        1
18.79         1
Name: count, Length: 2576, dtype: int64

In [89]:
df['current/discounted_price'].head(20)

0      89.68
1       9.99
2     314.00
3      77.00
4      77.00
5      77.00
6      77.00
7      77.00
8      16.99
9      77.00
10     14.99
11     77.00
12     29.99
13    249.99
14     69.95
15     77.00
16     39.97
17     14.49
18     16.98
19     77.00
Name: current/discounted_price, dtype: float64

In [90]:
(df['current/discounted_price'] < 0).sum()

np.int64(0)

In [91]:
df['price_on_variant'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: price_on_variant
Non-Null Count  Dtype
--------------  -----
42675 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [92]:
df['price_on_variant'].unique()

array(['basic variant price: 2.4GHz', 'basic variant price: nan',
       'basic variant price: $162.24', ...,
       'basic variant price: $33.00 off coupon applied',
       'basic variant price: $112.96', 'basic variant price: $1,054.05'],
      dtype=object)

In [93]:
df['price_on_variant'].value_counts()

price_on_variant
basic variant price: nan                          21031
basic variant price: 16 Count (Pack of 1)           582
basic variant price: $9.99                          324
basic variant price: $119.95                        298
basic variant price: $169.99                        264
                                                  ...
basic variant price: $90.00 off coupon applied        1
basic variant price: $880.95                          1
basic variant price: $88.11                           1
basic variant price: $23.04                           1
basic variant price: $13.88                           1
Name: count, Length: 3466, dtype: int64

In [94]:
df['price_on_variant'].isnull().sum()

np.int64(0)

In [95]:
df['price_on_variant'].head(20)

0      basic variant price: 2.4GHz
1         basic variant price: nan
2         basic variant price: nan
3     basic variant price: $162.24
4      basic variant price: $72.74
5      basic variant price: $99.95
6      basic variant price: $88.11
7      basic variant price: $23.04
8         basic variant price: nan
9     basic variant price: $284.05
10        basic variant price: nan
11    basic variant price: $880.95
12        basic variant price: nan
13        basic variant price: nan
14        basic variant price: nan
15     basic variant price: $17.45
16     basic variant price: $38.86
17        basic variant price: nan
18     basic variant price: $13.88
19     basic variant price: $33.51
Name: price_on_variant, dtype: object

In [96]:
df['price_on_variant'] = (
    df['price_on_variant']
    .str.extract(r'\$([\d,]+\.?\d*)')[0]
    .str.replace(',', '', regex=False)
)

df['price_on_variant'] = pd.to_numeric(
    df['price_on_variant'],
    errors='coerce'
)

In [97]:
df['price_on_variant'].head(20)

0        NaN
1        NaN
2        NaN
3     162.24
4      72.74
5      99.95
6      88.11
7      23.04
8        NaN
9     284.05
10       NaN
11    880.95
12       NaN
13       NaN
14       NaN
15     17.45
16     38.86
17       NaN
18     13.88
19     33.51
Name: price_on_variant, dtype: float64

In [98]:
df['price_on_variant'].isnull().sum()

np.int64(22604)

In [99]:
df['price_on_variant'].isnull().mean() * 100

np.float64(52.96777973052138)

In [100]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [101]:
df['listed_price'].isnull().sum()

np.int64(0)

In [102]:
df['listed_price'].unique()

array(['$159.00', '$15.99', '$349.00', 'No Discount', '$19.98', '$14.33',
       '$17.99', '$21.89', '$20.00', '$48.99', '$19.99', '$38.98',
       '$14.39', '$169.99', '$29.99', '$219.99', '$15.00', '$24.99',
       '$32.72', '$71.87', '$18.99', '$21.44', '$199.99', '$99.95',
       '$79.99', '$49.99', '$33.99', '$39.99', '$89.99', '$119.97',
       '$35.64', '$24.58', '$69.99', '$249.99', '$27.99', '$6.29',
       '$239.99', '$229.99', '$169.00', '$32.29', '$34.99', '$348.00',
       '$65.99', '$5.84', '$176.99', '$96.99', '$11.87', '$43.29',
       '$64.99', '$159.95', '$45.79', '$109.99', '$8.99', '$32.99',
       '$149.99', '$25.99', '$339.99', '$99.99', '$35.99', '$449.00',
       '$76.99', '$165.00', '$13.33', '$7.79', '$30.00', '$129.99',
       '$22.99', '$78.00', '$719.00', '$299.89', '$175.00', '$299.99',
       '$25.00', '$199.95', '$97.99', '$21.98', '$86.99', '$24.49',
       '$439.99', '$61.99', '$17.14', '$10.70', '$399.00', '$21.99',
       '$29.96', '$6.59', '$9.99', '$69.00', '$609.99', '$41.81',
       '$88.99', '$29.73', '$11.22', '$24.95', '$159.99', '$64.85',
       '$139.97', '$189.99', '$119.99', '$59.95', '$59.99', '$139.09',
       '$76.89', '$107.99', '$269.99', '$23.98', '$14.99', '$129.95',
       '$549.99', '$74.99', '$289.99', '$37.99', '$16.86', '$131.99',
       '$26.98', '$24.98', '$12.99', '$42.99', '$329.99', '$134.99',
       '$144.99', '$104.99', '$209.99', '$99.00', '$15.80', '$183.64',
       '$179.99', '$359.99', '$14.55', '$288.98', '$379.99', '$259.99',
       '$251.99', '$699.99', '$16.98', '$67.99', '$27.86', '$249.95',
       '$308.00', '$229.97', '$39.95', '$89.00', '$649.00', '$13.99',
       '$31.99', '$234.89', '$799.00', '$369.00', '$133.99', '$94.99',
       '$10.15', '$10.99', '$147.99', '$26.99', '$242.95', '$1,299.00',
       '$329.00', '$16.99', '$399.99', '$32.43', '$172.99', '$11.63',
       '$31.44', '$10.82', '$404.00', '$151.91', '$55.00', '$499.00',
       '$215.99', '$5.41', '$54.99', '$20.18', '$183.29', '$78.50',
       '$6.99', '$9.98', '$25.98', '$899.99', '$8.54', '$599.00',
       '$151.49', '$395.99', '$759.00', '$16.09', '$44.99', '$569.99',
       '$879.99', '$284.99', '$129.00', '$429.99', '$198.00', '$694.99',
       '$28.99', '$23.74', '$83.99', '$11.99', '$210.00', '$120.99',
       '$25.54', '$70.99', '$70.92', '$117.45', '$54.95', '$118.00',
       '$67.79', '$87.99', '$49.98', '$53.90', '$30.72', '$439.00',
       '$449.99', '$57.56', '$36.37', '$24.84', '$58.62', '$55.99',
       '$799.99', '$355.01', '$9.26', '$249.00', '$549.00', '$42.00',
       '$349.99', '$45.99', '$13.98', '$309.99', '$17.26', '$174.99',
       '$33.59', '$7.64', '$18.00', '$24.41', '$203.99', '$17.12',
       '$89.98', '$41.99', '$29.98', '$153.49', '$44.80', '$154.00',
       '$16.29', '$11.59', '$15.19', '$58.50', '$999.99', '$53.99',
       '$299.00', '$539.99', '$145.99', '$56.99', '$32.32', '$279.99',
       '$259.00', '$21.58', '$55.04', '$50.99', '$489.99', '$23.79',
       '$569.00', '$47.99', '$30.10', '$8.09', '$117.99', '$1,699.99',
       '$51.99', '$16.56', '$16.62', '$129.50', '$139.99', '$49.95',
       '$70.00', '$132.99', '$63.99', '$22.78', '$11.65', '$40.99',
       '$198.95', '$23.48', '$13.85', '$499.95', '$29.00', '$12.58',
       '$269.00', '$139.48', '$499.99', '$15.89', '$319.99', '$18.61',
       '$137.49', '$63.50', '$2,549.00', '$93.95', '$124.99', '$27.97',
       '$109.00', '$17.29', '$90.00', '$155.99', '$48.63', '$144.89',
       '$13.49', '$419.99', '$36.48', '$297.77', '$347.85', '$410.99',
       '$22.36', '$135.99', '$356.99', '$297.95', '$8.38', '$119.00',
       '$26.89', '$23.99', '$137.99', '$82.60', '$206.99', '$52.99',
       '$409.89', '$51.89', '$79.95', '$999.00', '$29.95', '$389.99',
       '$296.99', '$140.99', '$14.66', '$1,399.99', '$179.95', '$8.20',
       '$15.75', '$274.95', '$156.40', '$11.19', '$354.99', '$323.99',
       '$199.00', '$149.97', '$106.99', '$38.96', '$14.50', '$1,199.99',
       '$23.95', '$150.00', '$22.98', '$647.99', '$34.90', '$57.99',
       '$112.99', '$26.95', '$33.56', '$6.54', '$82.49', '$279.00',
       '$21.19', '$219.00', '$210.99', '$36.99', '$566.99', '$139.00',
       '$30.70', '$1,199.00', '$42.85', '$127.99', '$100.00', '$275.00',
       '$863.99', '$389.00', '$38.88', '$114.99', '$21.77', '$19.70',
       '$434.99', '$45.08', '$48.95', '$254.99', '$248.99', '$599.99',
       '$18.39', '$68.99', '$100.60', '$71.99', '$2,799.00', '$52.69',
       '$649.99', '$699.00', '$4,299.00', '$17.59', '$459.00', '$195.99',
       '$46.99', '$597.52', '$103.99', '$2,099.99', '$109.60', '$43.99',
       '$1,099.99', '$299.95', '$1,499.00', '$33.32', '$139.95', '$8.94',
       '$729.99', '$6.68', '$164.99', '$16.59', '$29.94', '$224.68',
       '$36.27', '$34.98', '$184.99', '$225.00', '$84.95', '$4,199.00',
       '$54.97', '$147.91', '$81.00', '$140.79', '$42.40', '$208.99',
       '$21.20', '$224.95', '$31.26', '$117.95', '$10.25', '$679.95',
       '$125.80', '$919.99', '$369.99', '$128.05', '$20.69', '$132.61',
       '$8.18', '$28.46', '$2,999.00', '$30.41', '$115.90', '$194.99',
       '$521.99', '$69.95', '$289.00', '$85.00', '$187.95', '$30.99',
       '$23.38', '$56.92', '$140.00', '$177.42', '$110.00', '$90.99',
       '$109.94', '$50.98', '$24.37', '$797.99', '$48.00', '$2,499.95',
       '$17.00', '$158.99', '$185.00', '$45.00', '$116.95', '$60.50',
       '$78.49', '$109.95', '$12.79', '$40.00', '$36.00', '$110.46',
       '$56.65', '$99.49', '$225.99', '$84.99', '$72.99', '$26.25',
       '$116.99', '$20.26', '$262.00', '$27.42', '$993.99', '$971.99',
       '$479.00', '$1,499.99', '$226.99', '$127.00', '$444.99', '$277.00',
       '$17.10', '$13.68', '$24.97', '$17.49', '$75.30', '$72.60',
       '$101.40', '$349.95', '$171.99', '$118.99', '$437.97', '$1,599.00',
       '$171.95', '$350.00', '$3,399.00', '$59.90', '$372.99', '$464.07',
       '$29.50', '$192.00', '$20.99', '$19.97', '$102.99', '$53.00',
       '$89.95', '$525.00', '$204.69', '$21.13', '$20.94', '$149.00',
       '$339.00', '$52.00', '$47.95', '$1,299.99', '$61.20', '$311.25',
       '$104.00', '$102.81', '$164.00', '$179.00', '$271.99', '$129.97',
       '$42.80', '$54.08', '$37.11', '$608.80', '$152.99', '$326.72',
       '$21.18', '$17.98', '$265.99', '$18.05', '$93.99', '$50.68',
       '$253.00', '$3,099.00', '$259.95', '$294.00', '$9.97', '$6.38',
       '$786.80', '$42.49', '$3,599.00', '$400.99', '$13.60', '$35.00',
       '$82.50', '$81.85', '$108.99', '$9.71', '$31.02', '$274.99',
       '$719.90', '$326.99', '$144.49', '$419.00', '$597.99', '$191.02',
       '$82.99', '$114.27', '$390.00', '$6.48', '$8.10', '$659.00',
       '$120.00', '$749.99', '$1,212.64', '$448.96', '$1,799.99',
       '$223.50', '$333.00', '$78.59', '$159.98', '$849.99', '$14.15',
       '$162.99', '$285.00', '$42.93', '$76.00', '$91.99', '$29.67',
       '$16.15', '$34.80', '$49.00', '$12.74', '$4,299.99', '$38.69',
       '$62.34', '$37.76', '$149.95', '$7.93', '$42.97', '$244.99',
       '$31.95', '$7.92', '$1,295.00', '$368.48', '$48.97', '$20.11',
       '$519.99', '$329.95', '$2,599.00', '$829.99', '$123.49', '$319.00',
       '$113.99', '$60.99', '$19.67', '$360.00', '$33.08', '$122.95',
       '$45.17', '$889.00', '$26.78', '$40.10', '$36.11', '$324.99',
       '$869.99', '$2,519.00', '$117.02', '$168.00', '$50.39', '$21.08',
       '$424.99', '$38.25', '$218.00', '$829.95', '$1,349.00', '$239.95',
       '$31.29', '$7.99', '$975.98', '$325.86', '$84.90', '$23.50',
       '$49.60', '$145.80', '$204.99', '$8.98', '$175.95', '$2,499.99',
       '$31.19', '$184.00', '$177.00', '$521.00', '$28.30', '$10.61',
       '$879.00', '$10.80', '$190.00', '$101.64', '$28.81', '$25.55',
       '$78.99', '$19.66', '$24.08', '$14.98', '$94.95', '$81.99',
       '$27.00', '$169.98', '$54.59', '$126.99', '$157.99', '$38.00',
       '$35.98', '$13.28', '$9.50', '$23.00', '$99.98', '$125.12',
       '$38.05', '$12.62', '$109.97', '$128.99', '$37.00', '$333.99',
       '$4,198.00', '$142.99', '$166.99', '$56.86', '$107.30', '$684.99',
       '$32.41', '$16.49', '$73.99', '$9.96', '$9.49', '$959.94',
       '$220.99', '$197.95', '$148.00', '$234.99', '$5.95', '$1,249.99',
       '$53.49', '$314.60', '$7.18', '$275.99', '$246.99', '$399.84',
       '$12.84', '$12.97', '$11.91', '$41.90', '$32.95', '$87.78',
       '$394.99', '$226.00', '$24.91', '$21.95', '$197.99', '$1,469.00',
       '$352.95', '$189.00', '$66.57', '$10.49', '$119.95', '$39.57',
       '$209.95', '$130.00', '$59.00', '$238.90', '$19.90', '$143.95',
       '$399.90', '$7.00', '$19.80', '$31.88', '$51.98', '$246.00',
       '$8.95', '$7.86', '$359.00', '$308.48', '$9.80', '$16.51',
       '$239.00', '$298.00', '$174.95', '$399.95', '$176.89', '$41.67',
       '$322.49', '$383.99', '$229.00', '$84.97', '$18.98', '$204.98',
       '$59.59', '$77.95', '$5.48', '$187.98', '$174.21', '$161.99',
       '$79.00', '$14.29', '$409.95', '$21.50', '$74.95', '$237.71',
       '$29.38', '$58.99', '$134.95', '$81.07', '$674.99', '$179.90',
       '$528.59', '$52.50', '$98.00', '$126.49', '$27.07', '$354.00',
       '$31.66', '$1,533.00', '$52.24', '$189.95', '$343.34', '$15.98',
       '$5.49', '$220.00', '$27.33', '$167.95', '$8.65', '$12.60',
       '$2,399.99', '$429.00', '$38.99', '$29.42', '$14.91', '$75.51',
       '$18.12', '$23.96', '$82.47', '$309.00', '$4.95', '$26.66',
       '$64.95', '$167.70', '$2,279.99', '$495.00', '$729.00', '$52.49',
       '$143.99', '$263.50', '$18.95', '$202.00', '$22.61', '$7.19',
       '$8.89', '$154.99', '$629.00', '$28.29', '$50.00', '$49.59',
       '$451.99', '$36.44', '$669.99', '$25.63', '$9.39', '$123.37',
       '$8.92', '$495.96', '$10.64', '$185.99', '$194.95', '$21.60',
       '$439.95', '$20.82', '$14.24', '$109.34', '$579.99', '$309.95',
       '$200.00', '$541.95', '$145.48', '$508.00', '$17.78', '$24.86',
       '$13.16', '$27.95', '$24.75', '$41.95', '$461.00', '$3,199.99',
       '$34.95', '$5,399.00', '$1,049.00', '$919.00', '$469.99', '$39.18',
       '$2,299.99', '$224.99', '$313.99', '$98.99', '$66.00', '$20.98',
       '$42.50', '$116.00', '$199.39', '$138.99', '$52.94', '$79.02',
       '$949.99', '$116.64', '$2,199.99', '$22.00', '$50.37', '$74.93',
       '$33.90', '$122.00', '$85.99', '$226.51', '$4,995.95', '$21.00',
       '$16.61', '$25.49', '$66.01', '$14.97', '$36.98', '$26.81',
       '$13.51', '$66.22', '$2,239.95', '$48.62', '$283.99', '$23.26',
       '$569.95', '$36.97', '$464.40', '$609.00', '$1,599.99', '$15.96',
       '$1,129.99', '$92.99', '$2,899.00', '$16.97', '$2,999.99', '$9.10',
       '$1,749.99', '$21.39', '$599.95', '$139.98', '$149.98', '$950.43'],
      dtype=object)

In [103]:
df['listed_price'].head(20)

0         $159.00
1          $15.99
2         $349.00
3     No Discount
4     No Discount
5     No Discount
6     No Discount
7     No Discount
8     No Discount
9     No Discount
10    No Discount
11    No Discount
12    No Discount
13    No Discount
14    No Discount
15    No Discount
16    No Discount
17    No Discount
18    No Discount
19    No Discount
Name: listed_price, dtype: object

In [104]:
df['listed_price'].value_counts()

listed_price
No Discount    30364
$79.99           500
$29.99           406
$16.61           360
$23.26           283
               ...
$42.50             1
$2,999.99          1
$16.97             1
$71.87             1
$14.33             1
Name: count, Length: 911, dtype: int64

In [105]:
df['listed_price'] = df['listed_price'].str.extract(r'\$([\d,]+\.?\d*)')[0].str.replace(",","",regex=False)

In [106]:
df['listed_price'] = pd.to_numeric(df['listed_price'], errors='coerce')

In [107]:
df['listed_price'].isnull().sum()

np.int64(30364)

In [108]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [109]:
df['is_best_seller'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: is_best_seller
Non-Null Count  Dtype
--------------  -----
42675 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [110]:
df['is_best_seller'].value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

In [111]:
df['is_best_seller'].head(20)

0        No Badge
1        No Badge
2        No Badge
3     Best Seller
4        No Badge
5     Best Seller
6        No Badge
7     Best Seller
8        No Badge
9     Best Seller
10    Best Seller
11    Best Seller
12       No Badge
13       No Badge
14       No Badge
15    Best Seller
16    Best Seller
17    Best Seller
18    Best Seller
19       No Badge
Name: is_best_seller, dtype: object

In [112]:
df['is_best_seller'].unique()

array(['No Badge', 'Best Seller', "Amazon's", 'Limited time deal',
       'Save 30%', 'Save 12%', 'Save 9%', 'Save 17%', 'Save 77%',
       'Ends in', 'Save 10%', 'Save 18%'], dtype=object)

In [113]:
df.rename(columns={'is_best_seller': 'badge_type'}, inplace=True)

In [114]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [115]:
df['badge_type'] = df['badge_type'].str.strip()

In [116]:
df['badge_type'].value_counts()

badge_type
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

In [117]:
df['is_sponsored'].isnull().sum()

np.int64(0)

In [118]:
df['is_sponsored'].unique()

array(['Sponsored', 'Organic'], dtype=object)

In [119]:
df['is_sponsored'].value_counts()

is_sponsored
Organic      35664
Sponsored     7011
Name: count, dtype: int64

In [120]:
df['is_sponsored'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: is_sponsored
Non-Null Count  Dtype
--------------  -----
42675 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [121]:
df['is_sponsored'].head(20)

0     Sponsored
1     Sponsored
2     Sponsored
3       Organic
4       Organic
5       Organic
6       Organic
7       Organic
8       Organic
9       Organic
10      Organic
11      Organic
12    Sponsored
13    Sponsored
14    Sponsored
15      Organic
16      Organic
17      Organic
18      Organic
19      Organic
Name: is_sponsored, dtype: object

In [122]:
df['is_couponed'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: is_couponed
Non-Null Count  Dtype
--------------  -----
42675 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [123]:
df['is_couponed'].isnull().sum()

np.int64(0)

In [124]:
df['is_couponed'].unique()

array(['Save 15%  with coupon', 'No Coupon', 'Save 50%  with coupon',
       'Save $16.00  with coupon', 'Save $10.00  with coupon',
       'Save 10%  with coupon', 'Save $20.00  with coupon',
       'Save $4.00  with coupon', 'Save $0.33  with coupon',
       'Save $18.00  with coupon', 'Save 5%  with coupon',
       'Save $2.00  with coupon', 'Save $15.00  with coupon',
       'Save 6%  with coupon', 'Save $8.00  with coupon',
       'Save $40.00  with coupon', 'Save $1.50  with coupon',
       'Save 7%  with coupon', 'Save 20%  with coupon',
       'Save $1.00  with coupon', 'Save $5.00  with coupon',
       'Save $30.00  with coupon', 'Save $12.00  with coupon',
       'Save 25%  with coupon', 'Save $133.00  with coupon',
       'Save $50.00  with coupon', 'Save $11.00  with coupon',
       'Save 30%  with coupon', 'Save $3.00  with coupon',
       'Save 40%  with coupon', 'Save $25.00  with coupon',
       'Save $13.00  with coupon',
       'Save 25%  with coupon (some sizes/colors)',
       'Save $29.00  with coupon', 'Save 8%  with coupon',
       'Save $69.00  with coupon', 'Save $100.00  with coupon',
       'Save $45.00  with coupon', 'Save $120.00  with coupon',
       'Save $90.00  with coupon', 'Save $60.00  with coupon',
       'Save $33.00  with coupon'], dtype=object)

In [125]:
df['is_couponed'].value_counts()

is_couponed
No Coupon                                    40727
Save $16.00  with coupon                       438
Save 15%  with coupon                          398
Save 10%  with coupon                          218
Save 5%  with coupon                           191
Save 50%  with coupon                          123
Save $11.00  with coupon                       120
Save $100.00  with coupon                       97
Save 40%  with coupon                           96
Save $25.00  with coupon                        65
Save $30.00  with coupon                        49
Save $69.00  with coupon                        31
Save 8%  with coupon                            18
Save $10.00  with coupon                        14
Save $33.00  with coupon                        13
Save 20%  with coupon                            9
Save $20.00  with coupon                         9
Save $18.00  with coupon                         8
Save $45.00  with coupon                         5
Save $15.00  with coupon                         5
Save $1.00  with coupon                          4
Save $4.00  with coupon                          4
Save $2.00  with coupon                          3
Save $12.00  with coupon                         3
Save 25%  with coupon                            3
Save $60.00  with coupon                         2
Save $8.00  with coupon                          2
Save $40.00  with coupon                         2
Save $5.00  with coupon                          2
Save $50.00  with coupon                         2
Save $1.50  with coupon                          2
Save 6%  with coupon                             2
Save $0.33  with coupon                          1
Save 7%  with coupon                             1
Save $133.00  with coupon                        1
Save $29.00  with coupon                         1
Save $13.00  with coupon                         1
Save $3.00  with coupon                          1
Save 30%  with coupon                            1
Save 25%  with coupon (some sizes/colors)        1
Save $90.00  with coupon                         1
Save $120.00  with coupon                        1
Name: count, dtype: int64

In [126]:
df.rename(columns={"is_couponed":"couponed_info"},inplace=True)

In [127]:
df['couponed_info'] = df['couponed_info'].str.replace(r'\s+', ' ', regex=True)

In [128]:
df['couponed_info'] = df['couponed_info'].str.strip()

In [129]:
df['couponed_info'].unique()

array(['Save 15% with coupon', 'No Coupon', 'Save 50% with coupon',
       'Save $16.00 with coupon', 'Save $10.00 with coupon',
       'Save 10% with coupon', 'Save $20.00 with coupon',
       'Save $4.00 with coupon', 'Save $0.33 with coupon',
       'Save $18.00 with coupon', 'Save 5% with coupon',
       'Save $2.00 with coupon', 'Save $15.00 with coupon',
       'Save 6% with coupon', 'Save $8.00 with coupon',
       'Save $40.00 with coupon', 'Save $1.50 with coupon',
       'Save 7% with coupon', 'Save 20% with coupon',
       'Save $1.00 with coupon', 'Save $5.00 with coupon',
       'Save $30.00 with coupon', 'Save $12.00 with coupon',
       'Save 25% with coupon', 'Save $133.00 with coupon',
       'Save $50.00 with coupon', 'Save $11.00 with coupon',
       'Save 30% with coupon', 'Save $3.00 with coupon',
       'Save 40% with coupon', 'Save $25.00 with coupon',
       'Save $13.00 with coupon',
       'Save 25% with coupon (some sizes/colors)',
       'Save $29.00 with coupon', 'Save 8% with coupon',
       'Save $69.00 with coupon', 'Save $100.00 with coupon',
       'Save $45.00 with coupon', 'Save $120.00 with coupon',
       'Save $90.00 with coupon', 'Save $60.00 with coupon',
       'Save $33.00 with coupon'], dtype=object)

In [130]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'couponed_info', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [131]:
df['buy_box_availability'].unique()

array(['Add to cart', 'Unknown'], dtype=object)

In [132]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    28022
Unknown        14653
Name: count, dtype: int64

In [133]:
df['buy_box_availability'].isnull().sum()

np.int64(0)

In [134]:
df['buy_box_availability'].head()

0    Add to cart
1    Add to cart
2    Add to cart
3        Unknown
4        Unknown
Name: buy_box_availability, dtype: object

In [135]:
df['buy_box_availability'] = df['buy_box_availability'].str.strip()

In [136]:
df['buy_box_availability'].head(20)

0     Add to cart
1     Add to cart
2     Add to cart
3         Unknown
4         Unknown
5         Unknown
6         Unknown
7         Unknown
8         Unknown
9         Unknown
10    Add to cart
11        Unknown
12    Add to cart
13    Add to cart
14    Add to cart
15        Unknown
16    Add to cart
17    Add to cart
18    Add to cart
19        Unknown
Name: buy_box_availability, dtype: object

In [137]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'couponed_info', 'buy_box_availability',
       'delivery_details', 'collected_at'],
      dtype='object')

In [138]:
df['delivery_details'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: delivery_details
Non-Null Count  Dtype
--------------  -----
42675 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [139]:
df['delivery_details'].unique()

array(['Mon, Sep 1', 'Fri, Aug 29', 'Sep 1 - 11', 'Sep 4 - 9',
       'Sep 8 - 30', 'Aug 28 - Sep 1', 'Sep 1 - 2', 'Aug 28 - Sep 3',
       'Sep 1 - 9', 'Aug 29 - Sep 2', 'Sep 9 - 25', 'Aug 29 - Sep 12',
       'Sep 1 - 3', 'Tue, Sep 2', 'Sep 1 - 4', 'Sep 1 - 12',
       'Aug 29 - Sep 3', 'Sep 3 - 11', 'Sep 3 - 15', 'Sep 1 - 8',
       'Aug 29 - Sep 4', 'Sep 3 - 23', 'Sep 8 - 26', 'Sep 8 - 25',
       'Sep 8 - Oct 7', 'Sep 8 - 24', 'Sep 22 - Nov 4', 'Aug 27 - Sep 1',
       'Sep 8 - 23', 'Sep 1 - 17', 'Sep 8 - 22', 'Sep 2 - 11',
       'Sep 4 - 25', 'Sep 5 - 16', 'Aug 29 - Sep 11', 'Sep 8 - 17',
       'Sep 2 - 9', 'Sep 10 - 24', 'Sep 9 - 26', 'Sep 15 - 26',
       'Sep 8 - 16', 'Sep 9 - 16', 'Sep 2 - 15', 'Aug 28 - Sep 2',
       'Sep 9 - 23', 'Sep 15 - 30', 'Sep 5 - 15', 'Sep 3 - 9',
       'Sep 5 - 29', 'Sep 16 - Oct 3', 'Sep 8 - Oct 1', 'Sep 4 - 12',
       'Sep 17 - Oct 28', 'Fri, Sep 19', 'Sep 8 - 19', 'Sep 8 - 18',
       'Sep 5 - 23', 'Aug 28 - Sep 4', 'Mon, Sep 8', 'Sep 8 - Oct 3',
       'Sep 9 - Oct 3', 'Sep 15 - 29', 'Sep 4 - 16', 'Sep 15 - Oct 24',
       'Sep 8 - 29', 'Sep 2 - 4', 'Sep 4 - 11', 'Sep 12 - 30',
       'Aug 27 - Sep 2', 'Aug 29 - Sep 1', 'Sep 10 - 30', 'Sep 8 - 11',
       'Sep 3 - 16', 'Sep 1 - 16', 'Thu, Sep 11', 'Thu, Sep 4',
       'Sep 2 - 10', 'Fri, Sep 5', 'Thu, Aug 28', 'Fri, Sep 12',
       'Sep 17 - Oct 1', 'Wed, Sep 10', 'Sep 12 - Oct 6', 'Sep 2 - 8',
       'Sep 15 - Oct 1', 'Tue, Sep 9', 'Sep 22 - Oct 14', 'Wed, Sep 3',
       'Sep 1 - 15', 'Sep 3 - 10', 'Sep 3 - 12', 'Sep 19 - Oct 30',
       'Sep 10 - 17', 'Sep 10 - 18', 'Sep 11 - Oct 10', 'Mon, Sep 15',
       'Sep 8 - 15', 'Sep 12 - 23', 'Sep 2 - 16', 'Sep 12 - Oct 1',
       'Sep 5 - 11', 'Sep 15 - 23', 'Sep 5 - 24', 'Sep 3 - 18',
       'Sep 19 - Oct 1', 'Sep 2 - 3', 'Sep 11 - 29', 'Sep 22 - Nov 3',
       'Sep 17 - Oct 7', 'Sep 3 - 4', 'Sep 8 - 12', 'Sep 9 - 12',
       'Sep 10 - Oct 2', 'Sep 11 - 22', 'Sep 8 - 10',
       'Fri, Sep 5Or fastest delivery Thu, Aug 28',
       'Thu, Sep 4Or fastest delivery Thu, Aug 28',
       'Tue, Sep 9Or fastest delivery Thu, Aug 28',
       'Thu, Sep 11Or fastest delivery Thu, Aug 28',
       'Mon, Sep 8Or fastest delivery Thu, Aug 28', 'Sep 12 - Oct 2',
       'Sep 10 - Oct 6', 'Sep 11 - Oct 9',
       'Mon, Sep 8Or fastest delivery Wed, Sep 3', 'Sep 9 - 15',
       'Sep 17 - Oct 8', 'Sep 5 - 9', 'Sep 11 - 30', 'Sep 10 - 29',
       'Sun, Aug 31', 'Sep 9 - 24', 'Sep 15 - Oct 3', 'Sep 29 - Oct 20',
       'Sep 15 - 25', 'Sep 16 - 29', 'Sep 16 - 30'], dtype=object)

In [140]:
df['delivery_details'].value_counts()

delivery_details
Thu, Sep 11                                  13200
Mon, Sep 1                                    8306
Thu, Sep 4                                    6293
Tue, Sep 2                                    4742
Tue, Sep 9                                    3239
                                             ...
Sep 19 - Oct 1                                   1
Mon, Sep 8Or fastest delivery Thu, Aug 28        1
Sep 8 - 10                                       1
Sep 11 - Oct 9                                   1
Mon, Sep 8Or fastest delivery Wed, Sep 3         1
Name: count, Length: 136, dtype: int64

In [141]:
df['delivery_date'] = df['delivery_details'].str.extract(
    r'([A-Za-z]{3},?\s[A-Za-z]{3}\s\d{1,2}|\b[A-Za-z]{3}\s\d{1,2})'
)

In [142]:
df['delivery_range'] = df['delivery_details'].str.extract(
    r'(\d{1,2}\s*-\s*[A-Za-z]{3}\s*\d{1,2}|\b[A-Za-z]{3}\s\d{1,2}\s*-\s*\d{1,2})'
)

In [143]:
df['delivery_date'] = df['delivery_date'].str.strip()
df['delivery_range'] = df['delivery_range'].str.strip()

In [144]:
df.drop(columns=['delivery_details'], inplace=True)

In [145]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'couponed_info', 'buy_box_availability',
       'collected_at', 'delivery_date', 'delivery_range'],
      dtype='object')

In [146]:
df['delivery_date'].unique()

array(['Mon, Sep 1', 'Fri, Aug 29', 'Sep 1', 'Sep 4', 'Sep 8', 'Aug 28',
       'Aug 29', 'Sep 9', 'Tue, Sep 2', 'Sep 3', 'Sep 22', 'Aug 27',
       'Sep 2', 'Sep 5', 'Sep 10', 'Sep 15', 'Sep 16', 'Sep 17',
       'Fri, Sep 19', 'Mon, Sep 8', 'Sep 12', 'Thu, Sep 11', 'Thu, Sep 4',
       'Fri, Sep 5', 'Thu, Aug 28', 'Fri, Sep 12', 'Wed, Sep 10',
       'Tue, Sep 9', 'Wed, Sep 3', 'Sep 19', 'Sep 11', 'Mon, Sep 15',
       'Sun, Aug 31', 'Sep 29'], dtype=object)

In [147]:
df['delivery_date'].isnull().sum()

np.int64(0)

In [148]:
df['delivery_range'].unique()

array([nan, 'Sep 1 - 11', 'Sep 4 - 9', 'Sep 8 - 30', '28 - Sep 1',
       'Sep 1 - 2', '28 - Sep 3', 'Sep 1 - 9', '29 - Sep 2', 'Sep 9 - 25',
       '29 - Sep 12', 'Sep 1 - 3', 'Sep 1 - 4', 'Sep 1 - 12',
       '29 - Sep 3', 'Sep 3 - 11', 'Sep 3 - 15', 'Sep 1 - 8',
       '29 - Sep 4', 'Sep 3 - 23', 'Sep 8 - 26', 'Sep 8 - 25',
       '8 - Oct 7', 'Sep 8 - 24', '22 - Nov 4', '27 - Sep 1',
       'Sep 8 - 23', 'Sep 1 - 17', 'Sep 8 - 22', 'Sep 2 - 11',
       'Sep 4 - 25', 'Sep 5 - 16', '29 - Sep 11', 'Sep 8 - 17',
       'Sep 2 - 9', 'Sep 10 - 24', 'Sep 9 - 26', 'Sep 15 - 26',
       'Sep 8 - 16', 'Sep 9 - 16', 'Sep 2 - 15', '28 - Sep 2',
       'Sep 9 - 23', 'Sep 15 - 30', 'Sep 5 - 15', 'Sep 3 - 9',
       'Sep 5 - 29', '16 - Oct 3', '8 - Oct 1', 'Sep 4 - 12',
       '17 - Oct 28', 'Sep 8 - 19', 'Sep 8 - 18', 'Sep 5 - 23',
       '28 - Sep 4', '8 - Oct 3', '9 - Oct 3', 'Sep 15 - 29',
       'Sep 4 - 16', '15 - Oct 24', 'Sep 8 - 29', 'Sep 2 - 4',
       'Sep 4 - 11', 'Sep 12 - 30', '27 - Sep 2', '29 - Sep 1',
       'Sep 10 - 30', 'Sep 8 - 11', 'Sep 3 - 16', 'Sep 1 - 16',
       'Sep 2 - 10', '17 - Oct 1', '12 - Oct 6', 'Sep 2 - 8',
       '15 - Oct 1', '22 - Oct 14', 'Sep 1 - 15', 'Sep 3 - 10',
       'Sep 3 - 12', '19 - Oct 30', 'Sep 10 - 17', 'Sep 10 - 18',
       '11 - Oct 10', 'Sep 8 - 15', 'Sep 12 - 23', 'Sep 2 - 16',
       '12 - Oct 1', 'Sep 5 - 11', 'Sep 15 - 23', 'Sep 5 - 24',
       'Sep 3 - 18', '19 - Oct 1', 'Sep 2 - 3', 'Sep 11 - 29',
       '22 - Nov 3', '17 - Oct 7', 'Sep 3 - 4', 'Sep 8 - 12',
       'Sep 9 - 12', '10 - Oct 2', 'Sep 11 - 22', 'Sep 8 - 10',
       '12 - Oct 2', '10 - Oct 6', '11 - Oct 9', 'Sep 9 - 15',
       '17 - Oct 8', 'Sep 5 - 9', 'Sep 11 - 30', 'Sep 10 - 29',
       'Sep 9 - 24', '15 - Oct 3', '29 - Oct 20', 'Sep 15 - 25',
       'Sep 16 - 29', 'Sep 16 - 30'], dtype=object)

In [149]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'couponed_info', 'buy_box_availability',
       'collected_at', 'delivery_date', 'delivery_range'],
      dtype='object')

In [150]:
df['collected_at'].unique()

array(['2025-08-21 11:14:29', '2025-08-21 11:14:46',
       '2025-08-21 11:14:47', ..., '2025-08-30 19:55:04',
       '2025-08-30 19:55:28', '2025-08-30 19:56:33'], dtype=object)

In [151]:
df['collected_at'].value_counts()

collected_at
2025-08-21 11:15:31    33
2025-08-21 11:15:58    33
2025-08-21 11:14:29    33
2025-08-21 11:16:09    33
2025-08-30 19:53:37    33
                       ..
2025-08-29 11:22:29     1
2025-08-27 08:04:15     1
2025-08-27 07:39:48     1
2025-08-24 22:26:13     1
2025-08-21 12:07:49     1
Name: count, Length: 1559, dtype: int64

In [152]:
df['collected_at'] = pd.to_datetime(df['collected_at'])

In [153]:
df['title'].head()

0    boya boyalink 2 wireless lavalier microphone f...
1    lisen usb c to lightning cable, 240w 4 in 1 ch...
2    dji mic 2 (2 tx + 1 rx + charging case), wirel...
3    apple airpods pro 2 wireless earbuds, active n...
4    apple airtag 4 pack. keep track of and find yo...
Name: title, dtype: object

### Handling Duplicates

In [154]:
df[df.duplicated()].shape

(0, 14)

In [155]:
df['title'].duplicated().sum()

np.int64(33868)

In [156]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'badge_type', 'is_sponsored', 'couponed_info', 'buy_box_availability',
       'collected_at', 'delivery_date', 'delivery_range'],
      dtype='object')

### Correcting datatypes

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    42675 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      42675 non-null  int64
 4   current/discounted_price  42675 non-null  float64
 5   price_on_variant          20071 non-null  float64
 6   listed_price              12311 non-null  float64
 7   badge_type                42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   couponed_info             42675 non-null  object
 10  buy_box_availability      42675 non-null  object
 11  collected_at              42675 non-null  datetime64[ns]
 12  delivery_date             42675 non-null  object
 13  delivery_range            2205 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(7)
memory usage: 4.6+ MB

In [158]:
df['badge_type'] = df['badge_type'].astype('category')
df['is_sponsored'] = df['is_sponsored'].astype('category')
df['couponed_info'] = df['couponed_info'].astype('category')
df['buy_box_availability'] = df['buy_box_availability'].astype('category')

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    42675 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      42675 non-null  int64
 4   current/discounted_price  42675 non-null  float64
 5   price_on_variant          20071 non-null  float64
 6   listed_price              12311 non-null  float64
 7   badge_type                42675 non-null  category
 8   is_sponsored              42675 non-null  category
 9   couponed_info             42675 non-null  category
 10  buy_box_availability      42675 non-null  category
 11  collected_at              42675 non-null  datetime64[ns]
 12  delivery_date             42675 non-null  object
 13  delivery_range            2205 non-null   object
dtypes: category(4), datetime64[ns](1), float64(4), int64(2), object(3)
memory usage: 3.4+ MB

## final validation

In [160]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant            22604
listed_price                30364
badge_type                      0
is_sponsored                    0
couponed_info                   0
buy_box_availability            0
collected_at                    0
delivery_date                   0
delivery_range              40470
dtype: int64

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    42675 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      42675 non-null  int64
 4   current/discounted_price  42675 non-null  float64
 5   price_on_variant          20071 non-null  float64
 6   listed_price              12311 non-null  float64
 7   badge_type                42675 non-null  category
 8   is_sponsored              42675 non-null  category
 9   couponed_info             42675 non-null  category
 10  buy_box_availability      42675 non-null  category
 11  collected_at              42675 non-null  datetime64[ns]
 12  delivery_date             42675 non-null  object
 13  delivery_range            2205 non-null   object
dtypes: category(4), datetime64[ns](1), float64(4), int64(2), object(3)
memory usage: 3.4+ MB

In [163]:
memory_after = df.memory_usage(deep=True).sum()/1024**2
print(memory_after)

14.922701835632324

In [164]:
df.to_csv(
    "amazon_products_sales_data_cleaned.csv",
    index=False
)