In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("amazon_products_sales_data_uncleaned.csv")

In [3]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-30 19:56:33

## Inspection of Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [5]:
df.describe().round()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
count,42675,41651,41651,39458,30926,42675,42675,42675,42675,42675,28022,30955,3408,42675,40606,42675
unique,8808,31,4413,59,2576,3466,911,12,2,42,1,298,16,8038,40606,1559
top,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.6 out of 5 stars,25,100+ bought in past month,29.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"Delivery Mon, Sep 1",Small Business,https://m.media-amazon.com/images/I/51Xr76m2WL...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-21 11:15:31
freq,744,6151,626,8801,825,21031,30364,40814,35664,40727,28022,6189,1341,1461,1,33

In [6]:
df.isnull().sum()

title                           0
rating                       1024
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [7]:
df[df.duplicated()].shape

(0, 16)

In [8]:
df.shape

(42675, 16)

In [9]:
df = df.drop(["image_url","product_url"], axis=1)

In [10]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'collected_at'],
      dtype='object')

# Handling Missing Values

##### Title

In [11]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'collected_at'],
      dtype='object')

In [12]:
df.isnull().sum()

title                           0
rating                       1024
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

#### ratings

In [13]:

df["rating"].isnull().sum()

np.int64(1024)

In [14]:
df["rating"].unique()

array(['4.6 out of 5 stars', '4.3 out of 5 stars', '4.8 out of 5 stars',
       '4.5 out of 5 stars', '4.0 out of 5 stars', '4.7 out of 5 stars',
       '4.2 out of 5 stars', '4.4 out of 5 stars', '4.1 out of 5 stars',
       '4.9 out of 5 stars', '3.9 out of 5 stars', '3.8 out of 5 stars',
       '2.8 out of 5 stars', '3.6 out of 5 stars', '3.7 out of 5 stars',
       '3.4 out of 5 stars', '3.5 out of 5 stars', nan,
       '5.0 out of 5 stars', '3.3 out of 5 stars', '2.4 out of 5 stars',
       '2.9 out of 5 stars', '3.2 out of 5 stars', '3.0 out of 5 stars',
       '1.0 out of 5 stars', '2.3 out of 5 stars', '3.1 out of 5 stars',
       '2.5 out of 5 stars', '2.7 out of 5 stars', '1.5 out of 5 stars',
       '2.6 out of 5 stars', '2.0 out of 5 stars'], dtype=object)

In [15]:
df["rating"].describe()

count                  41651
unique                    31
top       4.6 out of 5 stars
freq                    6151
Name: rating, dtype: object

In [16]:
df["rating"].value_counts()

rating
4.6 out of 5 stars    6151
4.4 out of 5 stars    5525
4.5 out of 5 stars    5359
4.7 out of 5 stars    4664
4.8 out of 5 stars    4230
4.3 out of 5 stars    2927
4.2 out of 5 stars    2837
4.1 out of 5 stars    1959
4.0 out of 5 stars    1465
3.9 out of 5 stars    1316
3.8 out of 5 stars    1083
5.0 out of 5 stars     995
4.9 out of 5 stars     704
3.6 out of 5 stars     666
3.7 out of 5 stars     604
3.2 out of 5 stars     363
3.5 out of 5 stars     242
3.4 out of 5 stars     216
3.0 out of 5 stars     148
2.0 out of 5 stars     143
2.7 out of 5 stars      15
1.5 out of 5 stars      15
3.3 out of 5 stars       6
2.8 out of 5 stars       4
1.0 out of 5 stars       4
2.4 out of 5 stars       3
2.9 out of 5 stars       2
3.1 out of 5 stars       2
2.3 out of 5 stars       1
2.5 out of 5 stars       1
2.6 out of 5 stars       1
Name: count, dtype: int64

In [17]:
df["rating"] = df['rating'].str.extract(r'(\d+\.\d+)').astype(float)

In [18]:
df["rating"] = df['rating'].fillna(df['rating'].median())

In [19]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### number_of_reviews

In [20]:
df["number_of_reviews"].describe()

count     41651
unique     4413
top          25
freq        626
Name: number_of_reviews, dtype: object

In [21]:
df["number_of_reviews"].value_counts()

number_of_reviews
25        626
1         524
8         478
17        409
30        409
         ...
48,468      1
72,360      1
67,965      1
53,340      1
8,962       1
Name: count, Length: 4413, dtype: int64

In [22]:
df['number_of_reviews'].head(10)

0       375
1     2,457
2     3,044
3    35,882
4    28,988
5    44,522
6    13,466
7    38,105
8     4,380
9     7,308
Name: number_of_reviews, dtype: object

In [23]:
df['number_of_reviews'] = (
    df['number_of_reviews']
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [24]:
df["number_of_reviews"].isnull().sum()

np.int64(1024)

In [25]:
df['number_of_reviews'].fillna(df["number_of_reviews"].median(), inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_23032\1412695407.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['number_of_reviews'].fillna(df["number_of_reviews"].median(), inplace=True)

In [26]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### bought_in_last_month

In [27]:
df["bought_in_last_month"].head()

0    300+ bought in past month
1     6K+ bought in past month
2     2K+ bought in past month
3    10K+ bought in past month
4    10K+ bought in past month
Name: bought_in_last_month, dtype: object

In [28]:
df["bought_in_last_month"].unique()

array(['300+ bought in past month', '6K+ bought in past month',
       '2K+ bought in past month', '10K+ bought in past month',
       '100K+ bought in past month', nan, '100+ bought in past month',
       '1K+ bought in past month', '500+ bought in past month',
       '80K+ bought in past month', '70K+ bought in past month',
       '50K+ bought in past month', '40K+ bought in past month',
       '60K+ bought in past month', '20K+ bought in past month',
       '30K+ bought in past month', '9K+ bought in past month',
       '50+ bought in past month', '5K+ bought in past month',
       'List Price:', '7K+ bought in past month',
       '4K+ bought in past month', 'Typical:',
       '200+ bought in past month', '8K+ bought in past month',
       'ESRB Rating: Everyone', '3K+ bought in past month',
       'No featured offers available', 'List:',
       'ESRB Rating: Rating Pending', '900+ bought in past month',
       '400+ bought in past month', '700+ bought in past month',
       'This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.',
       '800+ bought in past month', 'More Buying Choices',
       '600+ bought in past month', '($1,999.75$1,999.75/100 cm)',
       'Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.',
       'ESRB Rating: Everyone 10+', 'ESRB Rating: Adults Only',
       '($54.26$54.26/count)', 'New Price:', '($1,315.78$1,315.78/kg)',
       'Alexa Built-in devices let you talk directly to Alexa, allowing you to play music, control your smart home, get news, weather, and more using your voice.',
       '($4,813.00$4,813.00/100 cm)', '($433.33$433.33/count)',
       '($252.00$252.00/count)', '($1,080.00$1,080.00/kg)',
       '($46.81$46.81/oz)', '($828.56$828.56/kg)', '($53.33$53.33/count)',
       '($30.00$30.00/count)', '($766.33$766.33/in)',
       '90K+ bought in past month', '($2.18$2.18/count)',
       '($5.27$5.27/in)', '($179.99$179.99/count)', '($43.69$43.69/oz)',
       'Was:'], dtype=object)

In [29]:
import numpy as np

def clean_bought(x):
    if pd.isna(x):
        return np.nan

    x = str(x)

    if 'bought in past month' in x:
        num = x.split('+')[0]

        if 'K' in num:
            return float(num.replace('K', '')) * 1000

        return float(num)

    return np.nan

df['bought_in_last_month'] = df['bought_in_last_month'].apply(clean_bought)

In [30]:
df['bought_in_last_month'].isnull().sum()

np.int64(10511)

In [31]:
df['bought_in_last_month'].fillna(
    df['bought_in_last_month'].median(),
    inplace=True
)

C:\Users\akhil\AppData\Local\Temp\ipykernel_23032\1699490390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bought_in_last_month'].fillna(

In [32]:
df['bought_in_last_month'].isnull().sum()

np.int64(0)

In [33]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### current/discounted_price

In [46]:
df['current/discounted_price'].unique()

array(['89.68', '9.99', '314.00', ..., '1,579.99', '20.14', '1,252.29'],
      dtype=object)

In [49]:
df['current/discounted_price'].describe()

count     30926
unique     2576
top       29.99
freq        825
Name: current/discounted_price, dtype: object

In [50]:
df['current/discounted_price'] = pd.to_numeric(df['current/discounted_price'].str.replace(",",""), errors='coerce')

In [51]:
df['current/discounted_price'].fillna(df['current/discounted_price'].median(), inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_23032\1749864171.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['current/discounted_price'].fillna(df['current/discounted_price'].median(), inplace=True)

In [52]:
df['current/discounted_price'].isnull().sum()

np.int64(0)

In [54]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

#### buy_box_availabilty

In [65]:
df['buy_box_availability'].isnull().sum()

np.int64(14653)

In [66]:
df['buy_box_availability'].unique()

array(['Add to cart', nan], dtype=object)

In [67]:
df['buy_box_availability'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: buy_box_availability
Non-Null Count  Dtype
--------------  -----
28022 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [68]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    28022
Name: count, dtype: int64

In [69]:
df['buy_box_availability'].fillna("Unknown",inplace=True)

In [72]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details            11720
sustainability_badges       39267
collected_at                    0
dtype: int64

### delivery_details

In [73]:
df['delivery_details'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: delivery_details
Non-Null Count  Dtype
--------------  -----
30955 non-null  object
dtypes: object(1)
memory usage: 333.5+ KB

In [74]:
df['delivery_details'].unique()

array(['Delivery Mon, Sep 1', 'Delivery Fri, Aug 29', nan,
       'Delivery Sep 1 - 11', 'Delivery Sep 4 - 9', 'Delivery Sep 8 - 30',
       'Delivery Aug 28 - Sep 1', 'Delivery Sep 1 - 2',
       'Delivery Aug 28 - Sep 3', 'Delivery Sep 1 - 9',
       'Delivery Aug 29 - Sep 2', 'Delivery Sep 9 - 25',
       'Delivery Aug 29 - Sep 12', 'Delivery Sep 1 - 3',
       '$42.19 delivery', 'Delivery Tue, Sep 2', 'Delivery Sep 1 - 4',
       'Delivery Sep 1 - 12', 'Delivery Aug 29 - Sep 3',
       'Delivery Sep 3 - 11', 'Delivery Sep 3 - 15', '$41.20 delivery',
       '$40.35 delivery', 'Delivery Sep 1 - 8', 'Delivery Aug 29 - Sep 4',
       'Delivery Sep 3 - 23', 'Ships to Pakistan', '$73.42 delivery',
       '$40.34 delivery', 'Delivery Sep 8 - 26', '$58.05 delivery',
       'Delivery Sep 8 - 25', '$40.13 delivery', '$43.43 delivery',
       'Delivery Sep 8 - Oct 7', 'Delivery Sep 8 - 24',
       'Delivery Sep 22 - Nov 4', '$40.89 delivery', '$44.08 delivery',
       'Delivery Aug 27 - Sep 1', 'Delivery Sep 8 - 23',
       '$40.39 delivery', '$9.03 delivery Sep 8 - 22', '$41.77 delivery',
       'Delivery Sep 1 - 17', '$59.99 delivery Aug 28 - Sep 4',
       '$41.59 delivery', 'Delivery Sep 8 - 22', '$41.99 delivery',
       '$66.02 delivery Sep 3 - 8', 'Delivery Sep 2 - 11',
       '$57.80 delivery', '$63.99 delivery', 'Delivery Sep 4 - 25',
       'Delivery Sep 5 - 16', 'Delivery Aug 29 - Sep 11',
       'Delivery Sep 8 - 17', 'Delivery Sep 2 - 9',
       'Delivery Sep 10 - 24', '$46.68 delivery', 'Delivery Sep 9 - 26',
       'Delivery Sep 15 - 26', '$75.17 delivery', '$40.44 delivery',
       'Delivery Sep 8 - 16', 'Delivery Sep 9 - 16',
       'Delivery Sep 2 - 15', '$46.48 delivery',
       'Delivery Aug 28 - Sep 2', 'Delivery Sep 9 - 23',
       'Delivery Sep 15 - 30', 'Delivery Sep 5 - 15', '$178.71 delivery',
       'Delivery Sep 3 - 9', '$58.95 delivery', '$81.11 delivery',
       'Delivery Sep 5 - 29', '$64.58 delivery Sep 3 - 8',
       '$67.19 delivery', 'Delivery Sep 16 - Oct 3',
       'Delivery Sep 8 - Oct 1', 'Delivery Sep 4 - 12', '$49.02 delivery',
       'Delivery Sep 17 - Oct 28', 'Delivery Fri, Sep 19',
       'Delivery Sep 8 - 19', 'Delivery Sep 8 - 18',
       'Delivery Sep 5 - 23', 'Delivery Aug 28 - Sep 4',
       'Delivery Mon, Sep 8', 'Delivery Sep 8 - Oct 3',
       'Delivery Sep 9 - Oct 3', '$65.29 delivery',
       'Delivery Sep 15 - 29', '$241.54 delivery',
       '$6.93 delivery Sep 8 - 22', 'Delivery Sep 4 - 16',
       'Delivery Sep 15 - Oct 24', 'Delivery Sep 8 - 29',
       '$44.83 delivery', 'Delivery Sep 2 - 4', 'Delivery Sep 4 - 11',
       '$83.65 delivery', '$60.05 delivery Sep 3 - 8', '$57.26 delivery',
       '$71.18 delivery', 'Delivery Sep 12 - 30', '$69.19 delivery',
       'Delivery Aug 27 - Sep 2', 'Delivery Aug 29 - Sep 1',
       'Delivery Sep 10 - 30', 'Delivery Sep 8 - 11', '$65.19 delivery',
       'Delivery Sep 3 - 16', 'Delivery Sep 1 - 16', '$111.61 delivery',
       '$5.99 delivery Sep 12 - Oct 3', '$227.02 delivery',
       '$251.88 delivery Sep 8 - 22', 'Delivery Thu, Sep 11',
       '$42.43 delivery Sep 12 - Oct 2', '$54.41 delivery',
       '$140.09 delivery', '$101.48 delivery', '$49.94 delivery',
       '$43.73 delivery', '$40.37 delivery', '$55.86 delivery',
       '$43.93 delivery', '$35.31 delivery Sep 12 - Oct 2',
       '$42.70 delivery Aug 28 - Sep 4', 'Delivery Thu, Sep 4',
       'Delivery Sep 2 - 10', 'Delivery Fri, Sep 5',
       'Delivery Thu, Aug 28', 'Delivery Fri, Sep 12',
       'Delivery Sep 17 - Oct 1', 'Delivery Wed, Sep 10',
       '$10.89 delivery', 'Delivery Sep 12 - Oct 6', 'Delivery Sep 2 - 8',
       '$43.52 delivery', 'Delivery Sep 15 - Oct 1',
       '$42.70 delivery Aug 29 - Sep 5', '$39.79 delivery Sep 15 - Oct 3',
       'Delivery Tue, Sep 9', 'Delivery Sep 22 - Oct 14',
       '$59.70 delivery', '$285.30 delivery Sep 4 - 15',
       'Delivery Wed, Sep 3', '$5.99 delivery Sep 15 - Oct 6',
       '$40.80 delivery Sep 9 - 23', '$59.99 delivery Aug 29 - Sep 5',
       'Delivery Sep 1 - 15', 'Delivery Sep 3 - 10',
       'Delivery Sep 3 - 12', 'Delivery Sep 19 - Oct 30',
       '$49 delivery Sep 9 - 23', 'Delivery Sep 10 - 17',
       'Delivery Sep 10 - 18', '$17.49 delivery', '$61.55 delivery',
       'Delivery Sep 11 - Oct 10', '$48.12 delivery',
       'Delivery Mon, Sep 15', 'FREE delivery Sep 9 - 24',
       'Delivery Sep 8 - 15', 'Delivery Sep 12 - 23',
       'Delivery Sep 2 - 16', '$60.60 delivery Sep 12 - 29',
       '$118.24 delivery', '$42.59 delivery Sep 15 - Oct 6',
       'Delivery Sep 12 - Oct 1', 'Delivery Sep 5 - 11',
       'Delivery Sep 15 - 23', 'Delivery Sep 5 - 24',
       '$40.85 delivery Sep 9 - 23', 'Delivery Sep 3 - 18',
       'Delivery Sep 19 - Oct 1', 'Delivery Sep 2 - 3',
       '$70.80 delivery Sep 12 - 29', 'Delivery Sep 11 - 29',
       '$42.59 delivery Sep 15 - Oct 3', 'Delivery Sep 22 - Nov 3',
       '$108.33 delivery', '$251.45 delivery Sep 9 - 23',
       'Delivery Sep 17 - Oct 7', 'Delivery Sep 3 - 4',
       'Delivery Sep 8 - 12', 'Delivery Sep 9 - 12', '$146.58 delivery',
       '$70 delivery', 'Delivery Sep 10 - Oct 2', '$11.17 delivery',
       '$77.25 delivery Sep 9 - 24', 'Delivery Sep 11 - 22',
       'Delivery Sep 8 - 10', '$63.31 delivery',
       'Delivery Fri, Sep 5Or fastest delivery Thu, Aug 28',
       'Delivery Thu, Sep 4Or fastest delivery Thu, Aug 28',
       'Delivery Tue, Sep 9Or fastest delivery Thu, Aug 28',
       'Delivery Thu, Sep 11Or fastest delivery Thu, Aug 28',
       '$9.11 delivery', '$5.15 delivery Sep 15 - Oct 6',
       '$5.43 delivery Sep 15 - Oct 6',
       'Delivery Mon, Sep 8Or fastest delivery Thu, Aug 28',
       'Delivery Sep 12 - Oct 2', 'Delivery Sep 10 - Oct 6',
       '$48.44 delivery', '$8.09 delivery', 'Delivery Sep 11 - Oct 9',
       'Delivery Mon, Sep 8Or fastest delivery Wed, Sep 3',
       '$54.46 delivery', 'Delivery Sep 9 - 15',
       'Delivery Sep 17 - Oct 8', 'Delivery Sep 5 - 9',
       'Delivery Sep 11 - 30', 'Delivery Sep 10 - 29',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Sun, Aug 31',
       'FREE delivery Wed, Sep 3Or fastest delivery Sun, Aug 31',
       'FREE delivery Thu, Sep 4Or fastest delivery Wed, Sep 3',
       'FREE delivery Tue, Sep 9Or fastest delivery Thu, Sep 4',
       'FREE delivery Tomorrow, Aug 30',
       '$38.09 delivery Sep 4 - 8Or fastest delivery Thu, Sep 4',
       'FREE delivery Wed, Sep 3',
       'FREE delivery Sep 13 - 23Or fastest delivery Sep 13 - 19',
       'FREE delivery Sep 3 - 4',
       'FREE delivery Sep 4 - 9Or fastest delivery Sep 4 - 6',
       'FREE delivery Tue, Sep 9',
       'FREE delivery Wed, Sep 3Or fastest delivery Mon, Sep 1',
       'FREE delivery Sep 13 - 22Or fastest delivery Sep 13 - 18',
       'FREE delivery Sep 4 - 7Or fastest delivery Sep 4 - 5',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Mon, Sep 1',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Tue, Sep 2',
       'FREE delivery Fri, Sep 5',
       'FREE delivery Sep 5 - 9Or fastest delivery Tue, Sep 2',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 8',
       '$42.73 delivery',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 9',
       'Delivery Sun, Aug 31', 'FREE delivery Sep 4 - 8',
       'FREE delivery Sep 4 - 6Or fastest delivery Thu, Sep 4',
       'FREE delivery Thu, Sep 11',
       'FREE delivery Sep 12 - 22Or fastest delivery Sep 11 - 18',
       'FREE delivery Sep 4 - 7Or fastest delivery Sep 2 - 5',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Mon, Sep 1',
       'FREE delivery Sep 5 - 9', 'FREE delivery Sep 4 - 5',
       'FREE delivery Sep 3 - 5', 'FREE delivery Sep 15 - 18',
       'FREE delivery Sep 16 - 17', 'FREE delivery Tue, Sep 2',
       'FREE delivery Sep 4 - 8Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 9 - 11Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 5',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Tue, Sep 2',
       'FREE delivery Sep 9 - 12Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 5 - 9Or fastest delivery Sep 4 - 5',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Sun, Aug 31',
       'FREE delivery Thu, Sep 4',
       'FREE delivery Sep 8 - 12Or fastest delivery Tue, Sep 9',
       'FREE delivery Sep 11 - 22Or fastest delivery Sep 11 - 18',
       'FREE delivery Wed, Sep 3Or fastest delivery Tomorrow, Aug 30',
       'FREE delivery Sep 5 - 11Or fastest delivery Sep 4 - 8',
       'FREE delivery Wed, Sep 3 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Aug 30',
       'FREE delivery Tue, Sep 9Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 4 - 5Or fastest delivery Tue, Sep 2',
       'FREE delivery Tue, Sep 9 on $35 of items shipped by Amazon',
       'FREE delivery Sep 4 - 10Or fastest delivery Sep 4 - 7',
       'FREE delivery Sep 5 - 6Or fastest delivery Thu, Sep 4',
       '$59.99 delivery Sep 8 - 12', '$41.15 delivery',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Aug 31',
       'FREE delivery',
       'FREE delivery Sat, Sep 6Or fastest delivery Mon, Sep 1',
       'FREE delivery Thu, Sep 4Or fastest delivery Tomorrow, Aug 31',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by Amazon',
       'FREE delivery Sep 5 - 9Or fastest delivery Thu, Sep 4',
       'FREE delivery Fri, Sep 5Or fastest delivery Thu, Sep 4',
       'FREE delivery Sep 4 - 8Or fastest delivery Thu, Sep 4',
       'FREE delivery Mon, Sep 8',
       'FREE delivery Sep 5 - 9Or fastest delivery Wed, Sep 3',
       'FREE delivery Sep 5 - 10Or fastest delivery Thu, Sep 4',
       'Delivery Sep 9 - 24',
       'FREE delivery Sep 4 - 7Or fastest delivery Thu, Sep 4',
       'FREE delivery Fri, Sep 5 on $35 of items shipped by AmazonOr fastest delivery Wed, Sep 3',
       'Delivery Sep 15 - Oct 3',
       'FREE delivery Thu, Sep 4Or fastest delivery Mon, Sep 1',
       'FREE delivery Tomorrow 8\u202fAM - 8\u202fPM',
       'FREE delivery Fri, Sep 5Or fastest delivery Tue, Sep 2',
       'FREE delivery Sep 9 - 10', 'Delivery Sep 29 - Oct 20',
       'FREE delivery Thu, Sep 4Or fastest delivery Tue, Sep 2',
       'Delivery Sep 15 - 25', 'Delivery Sep 16 - 29',
       'Delivery Sep 16 - 30',
       'FREE delivery Sep 5 - 10Or fastest delivery Sep 4 - 6',
       'FREE delivery Sep 23 - Oct 18Or fastest delivery Sep 23 - Oct 13',
       'FREE delivery Thu, Sep 4 on $35 of items shipped by AmazonOr fastest delivery Wed, Sep 3'],
      dtype=object)

In [75]:
df['delivery_details'].describe()

count                   30955
unique                    298
top       Delivery Mon, Sep 1
freq                     6189
Name: delivery_details, dtype: object

In [77]:
df['delivery_details'].isnull().sum()

np.int64(11720)

In [78]:
df['delivery_details'] = df['delivery_details'].str.extract(r'Delivery\s+(.*)')

In [79]:
df['delivery_details'] = df['delivery_details'].ffill()

In [80]:
df.isnull().sum()

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price        0
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details                0
sustainability_badges       39267
collected_at                    0
dtype: int64

### sustainabilty_badges

In [81]:
df['sustainability_badges'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: sustainability_badges
Non-Null Count  Dtype
--------------  -----
3408 non-null   object
dtypes: object(1)
memory usage: 333.5+ KB

In [82]:
df['sustainability_badges'].describe()

count               3408
unique                16
top       Small Business
freq                1341
Name: sustainability_badges, dtype: object

In [85]:
df['sustainability_badges'].unique()

array(['Carbon impact', nan, 'Energy efficiency',
       'Safer chemicals +1 more', 'Small Business',
       '1 sustainability certification', 'Works with Alexa',
       'Manufacturing practices', 'Forestry practices', 'Alexa Built-in',
       'Energy efficiency +3 more', 'Recycled materials',
       'Safer chemicals +2 more', 'Energy efficiency +1 more',
       'Recycled materials +3 more', 'Recycled materials +2 more',
       'Made in Italy'], dtype=object)

In [86]:
df.drop('sustainability_badges', axis=1, inplace=True)

In [88]:
df.isnull().sum()

title                       0
rating                      0
number_of_reviews           0
bought_in_last_month        0
current/discounted_price    0
price_on_variant            0
listed_price                0
is_best_seller              0
is_sponsored                0
is_couponed                 0
buy_box_availability        0
delivery_details            0
collected_at                0
dtype: int64